In [30]:
import numpy as np 
from codes.Regression import Regression

In [34]:
regression = Regression(m=3, reg_param=0)
X = np.array([[1],[2],[3]])
X.shape
y = np.array([-1,1,1])
y.shape

(3,)

In [35]:
regression.gen_poly_features(X)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [36]:
regression = Regression(m=10, reg_param=0)


In [37]:
regression.w[0] = 1
regression.w[3] = 1
np.linalg.norm(regression.w)
regression.w

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [38]:
regression.loss_and_grad(X,y)

(267.3333333333333,
 array([[2.53333333e+01],
        [6.66666667e+01],
        [1.85333333e+02],
        [5.30666667e+02],
        [1.54533333e+03],
        [4.54666667e+03],
        [1.34653333e+04],
        [4.00506667e+04],
        [1.19465333e+05],
        [3.57026667e+05],
        [1.06834533e+06]]))

In [39]:
X_ = regression.gen_poly_features(X)

predict = np.dot(X_, regression.w)

error  = predict - np.vstack(y)

print(error, predict)

[[ 3.]
 [ 8.]
 [27.]] [[ 2.]
 [ 9.]
 [28.]]
